# Generated by Django 3.0.10 on 2020-12-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20200428_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_updated',
        ),
    ]
